### ISSUE TITLE
It shows error when you continue typing after changing difficulty

### ISSUE THREAD

**Issue by arpittyagi102** [arpittyagirocks/speedykeys#1]
When i click on easy difficulty and then try to type, it shows an error :
Cannot read properties of undefined (reading 'text');

**Comment by KaustubhTrivedi** [comment]
Assign this to me

**Comment by KaustubhTrivedi** [comment]
This issue is supposed to be closed right?

**Comment by arpittyagi102** [comment]
Yes! the problem has been solved, closing with this comment
